apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
    - host: kibana.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana-kibana
              servicePort: 5601
